### ISSUE TITLE
As a developer I would like to switch to SQL Server database for local development, to have a more robust database for the future of the project.

### ISSUE THREAD

**Issue by MikkelBKristensen** [ITU-BDSA23-GROUP20/Chirp#103]
Acceptance criteria:

* Change source code to use SQL Server instead of SQLite
* Make sure project builds with new SQL Server migrations
* Ensure that the tests are still running using SQLite in-memory and/or test containers.

**Comment by Qezert** [comment]
*Progress made so far:*

* Instead of using Sqlite with EF Core we now use SQLServer with EF Core
* The new connection string has (possibly) been obtained
* The new connection string has been added to appsettings.json
* Tests are still running on in-memory SQLite 

*Progress still to be made:*

* Make sure the connection string is correct
* Check if database is setup correctly
* Check that database is seeded correctly
* Get the project to actually build & run with the new setup

**Note: **

There might be more we need to do, but this is what we know right now.
